{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ include "metrics-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "metrics-agent.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
{{- end }}