{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "metrics-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "metrics-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}