{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics-agent.serviceAccountName" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
  {{- end -}}
